# Default configuration using unauthenticated MQTT broker and InfluxDB running on localhost.

# Autodiscovery is enabled by default, so all new devices will generate InfluxDB series,
# but you still need to configure your custom tags.

# This configuration will work when running esphome2influxdb as a script, but will be useless in Docker (localhost, eh?)

sources:
  - host: localhost

targets:
  - host: localhost
