# Default configuration using unauthenticated MQTT broker on 'mqtt' host,
# and InfluxDB running on 'influxdb' host,
# and no devices.

# This configuration will work both when running esphome2influxdb raw, and in Docker,
# assuming these hosts do in fact exist, run these services, and are resolvable
# (see https://docs.docker.com/config/containers/container-networking/ for details,
# look for '--dns' and related options).

sources:
  - host: mqtt

targets:
  - host: influxdb
